### ISSUE TITLE
PCB / BOM anomalies

### ISSUE THREAD

**Issue by Texy** [TOILmodular/Clouds#1]
Hi TOIL,
firstly, many thanks for sharing your work.
I've just started this build, using your BOM and gerbers.
I've not completed the build yet, but there are a couple of issues : 
1..QTY of 18pf caps in BOM is 4, but PCB silkscreen shows 6. I believe the BOM needs to be updated to 6.
2..QTY 8 22uF caps on BOM, but PCB silkscreen shows QTY 8 10uF. I believe 10uF is correct, so BOM needs updating.

Unfortunately I bought parts based on BOM values and quantities, but no big deal. I will need to fit those 22uF's, I wouldn't think it would be detrimental to the function of the module.
Thanks again,
Texy

**Comment by TOILmodular** [comment]
Thanks for the advice, Texy.
You are correct, I adjusted the BOM.
Hope, your build will be a success.
